version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - apt-get update
      - apt install jq
      - echo Installing source NPM dependencies...
      - cd simple-node-app
      - npm install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 176991310202.dkr.ecr.ap-southeast-1.amazonaws.com
      - REPOSITORY_URI=176991310202.dkr.ecr.ap-southeast-1.amazonaws.com/simple-node-app
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo Tagging the image as latest...
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - cd ..
  post_build:
    commands:
      - echo Updating task definition...
      - aws ecs describe-task-definition --task-definition simple-node-app --region ap-southeast-1 | jq .taskDefinition > taskdef.json
      - TASK_DEFINITION_ARN=$(aws ecs describe-task-definition --task-definition simple-node-app --region ap-southeast-1 | jq -r '.taskDefinition.taskDefinitionArn')
      - sed -i "s|<TASK_DEFINITION>|$TASK_DEFINITION_ARN|g" appspec_template.yaml > appspec.yaml
      - cat appspec.yaml
artifacts:
  files:
    - appspec.yaml
    - taskdef.json