version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing source NPM dependencies...
      - cd simple-node-app
      - npm install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 176991310202.dkr.ecr.ap-southeast-1.amazonaws.com
      - REPOSITORY_URI=176991310202.dkr.ecr.ap-southeast-1.amazonaws.com/simple-node-app
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo Tagging the image as latest...
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - cd ..
  post_build:
    commands:
      - echo list
      - ls -l
      - echo Updating task definition...
      - awk '{gsub(/<IMAGE_PLACEHOLDER>/, "176991310202.dkr.ecr.ap-southeast-1.amazonaws.com/simple-node-app:latest"); print}' taskdef.json > taskdef.tmp && mv taskdef.tmp taskdef.json
      - aws ecs register-task-definition --cli-input-json file://taskdef.json
      - export TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition simple-node-app | jq -r '.taskDefinition.taskDefinitionArn')
      - echo $TASK_DEFINITION
artifacts:
  files:
    - appspec.yaml
    - taskdef.json
  discard-paths: yes